Application/server/Controllers/InternalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

// This controller is made for Identity pages localization

namespace server.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class InternalController : ControllerBase
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult SwitchCulture([FromForm] string culture, string currentUrl)
        {
            Response.Cookies.Append(
                ".AspNetCore.Custom.Culture",
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );
            return LocalRedirect(currentUrl);
        }
    }
}

Application/server/Views/Shared/Components/SwitchCulture/Default.cshtml
@model server.Resources.SwitchCulture.SwitchCultureModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@*
    asp-controller + asp-action + asp-route{currentUrl} permite que el form apunte a "/Internal/Swithcultu/?return=..."
    de tal manera que al controlador llega el parametro "string currentUrl" directamente, y se puede redirigir a la currentUrl
    pero ya emitida una cookie actualizada con la culture seleccionada.
    como es un method=post el parametro de select (que es culture), no se envía en la url visiblemente si no que se envía
    escondido, asi que en el controlador se necesita acceder a ese parametro usando Request.Form["culture"] o más fácil aún
    usando "[FromForm]string culture" en la definicion de parametros del controlador, que mapea directamente.
    El tag select usa asp-for para mostrar su selección actual y asp-item para mostrar los items disponibles.
*@

@{
    var currentUrl = string.Concat(
        Context.Request.Path.ToUriComponent(), 
        Context.Request.QueryString.ToUriComponent());
}
<form method="post" class="px-2"
      asp-controller="Internal" asp-action="SwitchCulture" asp-route-currentUrl="@currentUrl">

    <select class="form-control form-control-sm"
            onchange="this.form.submit();"
            name="culture" asp-for="@Model.CurrentUICulture.Name" asp-items="@Model.SupportedCultures">
    </select>

</form>